"""Supervisor graph state — shared across all nodes in the LangGraph workflow."""

from __future__ import annotations

from typing import Annotated, Any, Optional, TypedDict, List
from pydantic import BaseModel, Field

from langgraph.graph.message import add_messages


def merge_dicts(left: dict | None, right: dict | None) -> dict:
    """Reducer for parallel branch dict updates."""
    merged = dict(left or {})
    merged.update(dict(right or {}))
    return merged


class AgentTask(BaseModel):
    """A single task delegated to an agent."""
    task_id: str = ""
    agent: str
    query: str
    depends_on: List[str] = Field(default_factory=list)


class ExecutionPlan(BaseModel):
    """The structured plan generated by the planner."""
    reasoning: str
    steps: List[AgentTask]
    parallel_groups: List[List[str]] = Field(default_factory=list)


class AgentResult(TypedDict):
    """The result returned by a specialist agent."""
    agent: str
    content: str
    symbols: List[str]
    data: Optional[dict]
    error: Optional[str]


class SupervisorState(TypedDict):
    """The state that flows through the entire LangGraph workflow."""

    # Input
    messages: Annotated[list, add_messages]
    user_id: str
    tenant_id: Optional[str]
    conversation_id: Optional[str]

    # Planning
    plan: Optional[ExecutionPlan]
    current_step: int

    # Execution
    agent_results: Annotated[dict[str, AgentResult], merge_dicts]
    pending_agents: List[str]
    task_status: Annotated[dict[str, str], merge_dicts]
    memory_context: List[dict]

    # Output
    final_response: Optional[str]
    follow_ups: List[str]
